local:
  dialect: postgres
  datasource: user=postgres password=postgres host=localhost port=5432 dbname=mstation_local sslmode=disable
  dir: migrations/schema
  table: migrations

env:
  dialect: postgres
  datasource: user=${DB_USER} password=${DB_PASS} host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} sslmode=${DB_SSLMODE}
  dir: migrations/schema
  table: migrations

e2e-test:
  dialect: postgres
  datasource: user=postgres password=postgres host=localhost port=5432 dbname=mstation_local sslmode=disable
  dir: migrations/schema
  table: migrations
